language: java
jdk:
- oraclejdk8

##########################
### BUILD WITH MAVEN
##########################
script:
# Once tests are properly set up remove skip tests
./kafka-java-console-sample/gradle check